apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: k6
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      httpMode: POST
      # InfluxDB 1.8 uses InfluxQL
      version: InfluxQL

